version: '2.1'

services:
  # master
  master:
    image: mysql:5.7.22
    ports:
      # Allow client to access 3306
      - "3306"
      - "13306:3306"
    volumes:
      - ./master/mnt/data:/mnt/data
      - ./master/var/lib/mysql:/var/lib/mysql
      - ./master/etc/mysql/mysql.conf.d:/etc/mysql/mysql.conf.d
      - ./master/var/log/mysql:/var/log/mysql
    env_file:
      - .env
    networks:
      app_net:
        ipv4_address: "${MASTER_IP}"
  # slave
  slave:
    image: mysql:5.7.22
    ports:
      # Allow client to access 3306
      - "3306"
      - "13307:3306"
    volumes:
      - ./slave/var/lib/mysql:/var/lib/mysql
      - ./slave/etc/mysql/mysql.conf.d:/etc/mysql/mysql.conf.d
      - ./slave/var/log/mysql:/var/log/mysql
    env_file:
      - .env
    networks:
      app_net:
        ipv4_address: "${SLAVE_IP}"

networks:
      app_net:
        driver: bridge
        enable_ipv6: false
        ipam:
          driver: default
          config:
          -
            subnet: 172.100.0.0/16